### ISSUE TITLE
Ontology target - no class prefix for schema unique property with local scope

### ISSUE THREAD

**Issue by jechterhoff** [ShapeChange/ShapeChange#103]
rule-owl-prop-localScopeAll ensures that all properties are generated with local scope, i.e. all of them have an rdfs:domain predicate. Add a subrule of rule-owl-prop-localScopeAll to control that the class prefix is omitted if the property is unique within the schema (the rdfs:domain shall still be created).

**Comment by denevers** [comment]
Maybe easier to have a specific rule to force domain ?

**Comment by jechterhoff** [comment]
At first glance, that would be easier. It would have side-effects on other rules, though, which can cause trouble later on. It's better to avoid that, I think.

**Comment by denevers** [comment]
Gotcha. You know better.

**Comment by denevers** [comment]
On second thought, maybe what I really need is universal quantification (owl:allValuesFrom) restriction.

**Comment by jechterhoff** [comment]
Well, just let us know what exactly you need. :-)

**Comment by denevers** [comment]
Should have been clearer : I think I already have what I need

**Comment by jechterhoff** [comment]
Ok, good. Then I'll close this issue. We can re-open it if necessary.
