### ISSUE TITLE
General - Recognise stereotype <<retired>>

### ISSUE THREAD

**Issue by cportele** [ShapeChange/ShapeChange#108]
The German mapping agencies use a stereotype `<<retired>>` on classifiers and properties to declare that a model element has been deprecated and only remains in the model for compatibility reasons.

In order to load the stereotype, the stereotype needs to be declared in Options.

**Comment by cportele** [comment]
Branch: https://github.com/ShapeChange/ShapeChange/tree/stereotype-retired

**Comment by jechterhoff** [comment]
Can we close this issue now?

**Comment by cportele** [comment]
Yes, sorry forgot the reference to the issue in the commit notes...
