### ISSUE TITLE
StandardMapEntries for CI_Responsibility

### ISSUE THREAD

**Issue by sgrellet** [ShapeChange/ShapeChange#144]
Is there a configuration entry for ISO 19115-1:2014 : CI_Responsibility ?
I haven't found it in ShapeChange-2.5.1\test\config
Thanks

**Comment by jechterhoff** [comment]
At the moment, there are only map entries for types from the first generation of the metadata standards.

**Comment by sgrellet** [comment]
ok. thanks. I'll correct by hand after ShapeChange first generation

**Comment by jechterhoff** [comment]
You may want to create a file with map entries for the types you need from ISO 19115-1:2014, and include that in the XmlSchema target configuration. The namespaces file would need to be updated as well.
