### ISSUE TITLE
UML taggedValue cannot be written to XML schema

### ISSUE THREAD

**Issue by yaozhihang** [ShapeChange/ShapeChange#146]
Hi, 

I'm currently using ShapeChange and Enterprise Architect 13.5 to convert my CityGML ADE EA-Model (.eap) to XML application schema (.xsd). 
With the ShapeChange version 2.3.0 everything works perfectly and all the taggedValues i've defined in my EA-model can be properly written to the target XML application schema like below:
```xml
... 
<element name="IndustrialBuilding" substitutionGroup="bldg:_AbstractBuilding" type="TestADE:IndustrialBuildingType">
    <annotation>
      <appinfo>
        <taggedValue xmlns="http://www.interactive-instruments.de/ShapeChange/AppInfo" tag="topLevel">true</taggedValue>
      </appinfo>
    </annotation>
</element>
...
```
However, when using the ShapeChange 2.4.0 or its higher versions (2.5.0 and 2.5.1), the taggedValues are mssing in the respective XML elements:
```xml
... 
<element name="IndustrialBuilding" substitutionGroup="bldg:_AbstractBuilding" type="TestADE:IndustrialBuildingType"/>
...
```  

You may reproduce the same issue with my EA-model and ShapeChange-Configuration file which are available via the following Github-link:
https://github.com/3dcitydb/extension-test-ade/tree/master/resources/uml

Could you advise me how to solve this problem?

Thanks in advance and best regards

Zhihang

**Comment by jechterhoff** [comment]
The defaultEncodingRule specified by your configuration is "city-gml". In order for tagged values specified by the input parameter "representTaggedValues" to be added to the XML Schema, the encoding rule needs to contain "rule-xsd-all-tagged-values" - which the city-gml encoding rule does not. That behaviour should be the same for ShapeChange v2.3.0. Are you sure that you are using the exact same configuration? 

The tagged values should appear in the XSD if you replace the line in your configuration file that defines the defaultEncodingRule target parameter with:

```xml
<targetParameter name="defaultEncodingRule" value="custom"/>
<rules>
   <EncodingRule extends="citygml-ade" name="custom">
      <rule name="rule-xsd-all-tagged-values"/>
   </EncodingRule>
</rules>
```

**Comment by yaozhihang** [comment]
Hi, thank you very much for your quick responce. 
I've modified my configuration file according to your hints and everything is working perfectly now!
ShapeChange is a great software tool.

**Comment by jechterhoff** [comment]
Hi. 
I'm glad it works as expected now. 
Thank you for the positive feedback!
