### ISSUE TITLE
Ontology target - default type implementation does not apply if no conversion rule for codelist is defined

### ISSUE THREAD

**Issue by denevers** [ShapeChange/ShapeChange#154]
I'm trying to run ShapeChange on GeoSciML 3.2 - it has been suggested during a GeoSciML that since it had less "XSD artefacts" than 4.1 it would made a cleaner OWL.

I keep getting those errors (for all classes with stereotype `<<CodeList>>`)

eg:
```
    <Error message="Could not find a type mapping and also no class within the model to map class 'MovementSenseTerm'.">
      <Detail message="--- Context - Property: Model::Domain Model::GeoSciML v3.2::GeoSciML::GeologicStructure::DisplacementValue::movementSense"/>
</Error>
```
This class is indeed in the model.

EAP and SC config here : https://github.com/opengeospatial/GeoSciML/tree/master/GeoSciMLv3.2

**Comment by jechterhoff** [comment]
So you can solve your problem by including rule-owl-cls-codelist-19150-2 in your encoding rule.

However, this issue identifies a bug in the current implementation: the default type implementation does not apply for types for which no conversion rule is defined. The internal logic for creating classes in the ontology target needs to be fixed.

**Comment by denevers** [comment]
thanks, will test later today

**Comment by denevers** [comment]
victory. Thanks
