### ISSUE TITLE
General - Make parameter replacement mechanism available for Transformers

### ISSUE THREAD

**Issue by ebadgley** [ShapeChange/ShapeChange#16]
As per conversations with Johannes: Parameter replacement works fine for input, log, and target configuration, but not for Transformers.  We would like the ability to replace transformer configuration values as well.

From Johannes: "Regarding replacement of transformation parameter values, we would need to extend ProcessConfiguration.java. Retrieval of parameter values should include replacing parameter values, and in order to do so a ProcessConfiguration needs to have access to Options. "

**Comment by jechterhoff** [comment]
Closing this very old issue. If the enhancement discussed in this issue is still needed, please reopen the issue.
