### ISSUE TITLE
Loading SCXML: input configuration parameters and elements should be taken into account 

### ISSUE THREAD

**Issue by pbirkel** [ShapeChange/ShapeChange#162]
Currently, loading from SCXML ignores most of the input configuration parameters and elements.  Loading from SCXML should support the "standard" input configuration parameters and elements, for example: input parameters like checkingConstraints.

**Comment by jechterhoff** [comment]
Input configuration items that so far have been ignored when loading SCXML:

- input parameters:
  - addTaggedValues
  - checkingConstraints
  - classTypesToCreateConstraintsFor
  - constraintCreationForProperties
  - dontConstructAssociationNames
  - excludePackages
  - loadConstraintsForSelectedSchemasOnly
  - prohibitLoadingClassesWithStatusTaggedValue
  - representTaggedValues
  - loadDiagrams
  - sortDiagramsByName
- tag aliases
- descriptor sources
- PackageInfo elements
- stereotype aliases

**Comment by jechterhoff** [comment]
Supported in ShapeChange v2.9.0.

Note: in order for descriptor sources to be applied, input configuration parameter [applyDescriptorSourcesWhenLoadingScxml](https://shapechange.net/get-started/config/input/#applyDescriptorSourcesWhenLoadingScxml) needs to be set to true.
