### ISSUE TITLE
Ontology target : different behaviors for UML tagged values as template for DescriptorTarget

### ISSUE THREAD

**Issue by rmitanch** [ShapeChange/ShapeChange#165]
Hi,
I'm facing a curious behavior with UML tagged values as template for DescriptorTarget

In my UML model, I define for a given object an owned tagged value "myTag" with value "myValue" (and I also have inherited tagged values from INSPIRE UML profile)
I try two kinds of target descriptors for target skos:closeMatch

- case A: template="[[TV:xsdEncodingValue]]" and I get iso1936_2007_INSPIRE_Extensions 
_the choice of such a tagged value for template is stupid, but it works !_

- case B: template="[[TV:myTag]]" and I get N/A 
_I should have myValue for the particular inspected entity_

_(complete target descriptor config is
DescriptorTarget target="skos:closeMatch" template="[[TV:myTag]]" noValueBehavior="populateOnce" noValueText="N/A" format="string")_
Of course, I first checked that the tagged value myTag/myValue is correctly defined for the given object within the UML model...

Any clue ?
Thanks in advance
Richard

**Comment by jechterhoff** [comment]
Hi Richard.

Most likely you haven't added the input parameter [addTaggedValues](https://shapechange.net/get-started/config/input/#addTaggedValues) or [representTaggedValues](https://shapechange.net/get-started/config/input/#representTaggedValues) to your configuration. Add one of these parameters, with your "myTag" as value - or a comma-separated list of tag names. Then the ontology target should no longer return N/A for it.

Background: ShapeChange does not load all tagged values from the model, only those that are well-known (see [here](https://shapechange.net/app-schemas/uml-profile/#Tagged_Values) - though that list is somewhat outdated). I guess that it would make life easier for some users if we had an input parameter like _addAllTaggedValues_ ...

**Comment by rmitanch** [comment]
Hi Johannes.

Thank you, I really appreciate your effort!
You're right, I omitted such input parameters, so now I have corrected my config file accordingly, but I still get a N/A return
it works now with a tag named "primitiveGraphique", but I still get N/A with some others declared the same way (?) : I suspect now the UML model, and maybe the way to declare the tags, either within profiles, or directly using EA "New Tagged Value"...

Thanks again
Richard

**Comment by jechterhoff** [comment]
Closing this issue since there has not been a reply for a long time.
