### ISSUE TITLE
Feature Catalogue in xml format

### ISSUE THREAD

**Issue by jrosleo** [ShapeChange/ShapeChange#168]
According to [gfc](http://www.isotc211.org/2005/gfc), something like [G_3](http://www.isotc211.org/2005/gfc/resources/example/G_3.xml) example. Could it be possible?

**Comment by cportele** [comment]
In principle, yes. We have created support for GFC output in a specialized feature catalogue target (https://github.com/ShapeChange/AAATools/blob/master/src/main/resources/xslt/aaa-xml-gfc.xsl). 

This could be used as a basis for a GFC output in the ShapeChange feature catalogue target. The XML input is a little different in the AAA feature catalogue target than in the ShapeChange feature catalogue target, so some changes are required.

**Comment by jrosleo** [comment]
Thank you Clemens. I will try the xslt but a direct export from ShapeChange would be great.
