### ISSUE TITLE
The semantic validation of th ShapeChange configuration detected one or more errors

### ISSUE THREAD

**Issue by tpaslou** [ShapeChange/ShapeChange#206]
Hello

I m posting this here since i cant find any related topic on google . 

![image](https://user-images.githubusercontent.com/31972235/64339573-09cadf80-cfed-11e9-9661-5cd6f0819c66.png)

I m getting this error and when i go to my log file i cant find any obvious problem . 

![image](https://user-images.githubusercontent.com/31972235/64339735-56161f80-cfed-11e9-9af6-9ad39cf766fb.png)

Any help would be much appreciated !

**Comment by pbirkel** [comment]
Recommend that you start by addressing the first error, which is that you can't use a 64-bit JRE with the EA7 input model.  Try again with a 32-bit JRE.  You may have to install that for yourself.

**Comment by tpaslou** [comment]
I ve already done that as you can see here

![image](https://user-images.githubusercontent.com/31972235/64340718-7d6dec00-cfef-11e9-8b4f-e2e26f5aa14d.png)

**Comment by pbirkel** [comment]
Yes, but evidently it is the x86_64 JRE that is being used.  Revise your BAT file to use an absolute path to get the 32-bit JRE.  Like this" "C:\Program Files (x86)\Java\jre1.8.0_221\bin\java"

**Comment by jechterhoff** [comment]
@tpaslou Which result do you get when you simply type `java -version` on your command line?

**Comment by tpaslou** [comment]
> Yes, but evidently it is the x86_64 JRE that is being used. Revise your BAT file to use an absolute path to get the 32-bit JRE. Like this" "C:\Program Files (x86)\Java\jre1.8.0_221\bin\java"

This solved my problems ! I had to execute it like this  :
"C:\Program Files (x86)\Java\jre1.8.0_221\bin\java.exe"  -jar ShapeChange-2.8.0.jar -Dfile.encoding=UTF-8 -c C:\Users\thano\Desktop\ShapeChange-2.8.0\inspire_config.xml 
in my .bat file .

Thank you for your time !
