### ISSUE TITLE
ArcGIS Workspace target - max name length should be configurable

### ISSUE THREAD

**Issue by jechterhoff** [ShapeChange/ShapeChange#22]
The maximum name length is currently hardcoded to 30 – any name longer than this will be clipped (a warning will be logged if that happens). Make the maximum name length configurable, so that the user can set a higher value (like 64).

**Comment by cportele** [comment]
According to http://desktop.arcgis.com/en/arcmap/latest/manage-data/administer-file-gdbs/file-geodatabase-size-and-name-limits.htm, the name restriction for a file gdb is 64 chars for field names and 160 chars for table names.

For databases the limit depends on the DBMS and is usually less. The limit of 30 comes from Oracle: http://desktop.arcgis.com/en/arcmap/latest/manage-data/gdbs-in-sql-server/enterprise-geodatabase-limits.htm

So, making it configurable seems reasonable, if the deployment environment is known.

**Comment by jechterhoff** [comment]
Realized by target parameter _maxNameLength_ (see [documentation](http://shapechange.net/targets/arcgis-workspace/#maxNameLength)).
