### ISSUE TITLE
How to generate <sc:taggedValue>

### ISSUE THREAD

**Issue by yaozhihang** [ShapeChange/ShapeChange#232]
Hi,

the UML taggedValue is per-default transformed to XSD-file in the form like the following:
```
    <annotation>
      <appinfo>
        <taggedValue xmlns="http://www.interactive-instruments.de/ShapeChange/AppInfo" tag="geometry">P,S</taggedValue>
      </appinfo>
    </annotation>
```

I would like to ask, if it is possible to generate the XML schema in a simple form like the following:
```
    <annotation>
      <appinfo>
        <sc:taggedValue tag="geometry">P,S</taggedValue>
      </appinfo>
    </annotation>
```

mayn thanks in advance,

Zhihang

**Comment by jechterhoff** [comment]
Well, if you ask whether there is a configuration option that would achieve the simple form, the answer is no. The source code would have to be changed, afaics.

**Comment by yaozhihang** [comment]
Thanks very much for the speedy reply. yeah, I'm asking for a configuration option for that. 
I thought there should exist such option, because I've seen this simple form in the Shapechange website https://shapechange.net/targets/xsd/extensions/nil/
It would be nice to have this option in future release of Shapechange.

**Comment by jechterhoff** [comment]
I'll see what we can do. It would probably be better to always encode annotation elements using the short form.

**Comment by jechterhoff** [comment]
Finally, I had time to work on this issue. The changes are in the `next` branch and will make it into the next release.
