### ISSUE TITLE
UML to RDF/TTL warning: cannot find application schema in UML file by schema name

### ISSUE THREAD

**Issue by nataschake** [ShapeChange/ShapeChange#258]
Hi, working with INSPIRE models I try to get RDF/TTL files for a particular application schema, namely Addresses. The UML model is taken from [its official site](https://inspire.ec.europa.eu/portfolio/data-models), ShapeChange configured for UML-to-RDF is taken from[ here](https://github.com/inspire-eu-rdf/inspire-rdf-vocabularies/tree/master/_generate/shapechange), particularly, the config file [ sc_inspire_rdf_ad.xml](https://github.com/inspire-eu-rdf/inspire-rdf-vocabularies/blob/master/_generate/shapechange/sc_inspire_rdf_ad.xml). Got the warning:

`None of the packages contained in the model is a schema selected for processing. Make sure that the schema you want to process are configured to be a schema (via the 'targetNamespace' tagged value or via a PackageInfo element in the configuration) and also selected for processing (if you use one of the input parameters appSchemaName, appSchemaNameRegex, appSchemaNamespaceRegex, ensure that they include the schema). Execution will stop now.`

ShapeChange INPUT is configured as:

```
<input id="INPUT">
  <parameter name="addTaggedValues" value="vocabulary,inspireConcept"/>
  <parameter name="inputModelType" value="EA7"/>
  **<parameter name="inputFile" value="model/INSPIRE.eap"/>**
  **<parameter name="appSchemaNamespaceRegex" value="http://inspire.ec.europa.eu/schemas/ad/.*"/>**
  <parameter name="publicOnly" value="true"/>
  <parameter name="checkingConstraints" value="enabled"/>
  <parameter name="oclConstraintTypeRegex" value="OCL"/>
  <parameter name="loadConstraintsForSelectedSchemasOnly" value="true"/>
  <parameter name="sortedSchemaOutput" value="true"/>
  <parameter name="excludedPackages" value="Foundation Schemas, Base Models, Annex II, Annex III"/>
  <parameter name="extractSeparator" value="--"/>
  <xi:include href="http://shapechange.net/resources/config/StandardAliases.xml"/>
  <xi:include href="http://shapechange.net/resources/config/DescriptorSourcesInspire.xml"/>
 </input> 
```
What is the problem?

**Comment by jechterhoff** [comment]
See my reply to your same question (more or less) on https://github.com/inspire-eu-rdf/inspire-rdf-vocabularies/issues/5
