### ISSUE TITLE
Default id column name in GeoPackage should be something else than _id

### ISSUE THREAD

**Issue by heidivanparys** [ShapeChange/ShapeChange#259]
The default id column name for the GeoPackage target is set to `_id`. However, in ArcGIS, that gives the error `HRESULT: 0x80042802`.

![image](https://user-images.githubusercontent.com/11427611/95203369-f3d8b100-07e2-11eb-80ca-7ae5dc5f8710.png)

I tested this with different names. The problem always seems to occur when the primary key column name starts with an underscore. I tested by converting a JSON file to GeoPackage via the GPKG driver of GDAL and using layer creation option FID to set the primary key column name.

`ogr2ogr output.gpkg -lco FID=_id mydata.json myfeaturetype`

When trying to understand what the exact error was, I found out that 0x80042802 has to be understood as a signed 32 bit integer, which gives -2147211262. Looking up that error code in https://resources.arcgis.com/en/help/arcobjects-java/api/arcobjects/constant-values.html and https://enterprise.arcgis.com/en/sdk/latest/windows/fdoError.html gives "Invalid column".

So the default name should be another one.

In the 1.3 specification, a note will be present regarding identifiers, see http://www.geopackage.org/spec/#_base and https://github.com/opengeospatial/geopackage/pull/542

So the default id column name should start with a lowercase character, not with an underscore.

**Comment by jechterhoff** [comment]
Thank you for the detailed issue report. I've switched the default value for parameter idColumnName from `_id` to simply `id`. The next release will contain this change.
