### ISSUE TITLE
NamingModifier Transformation: rule-trf-add-suffix and class stereotype

### ISSUE THREAD

**Issue by pbirkel** [ShapeChange/ShapeChange#279]
It appears to me that rule-trf-add-suffix is incomplete as it’s not sensitive to the applied class stereotype.  I think that it should _not_ apply to the attributes of classes stereotypes "enumeration" and "codelist".  I believe that, for example, in the context of the SqlDdl target (my current application) that there can never be a problem with a Key Word conflict in such cases as they always result in a quoted string in an INSERT statement.

For example, in the current situation using the SqlDdl target with a suffix value="_pim" we get:

_INSERT INTO iso19100.sv_parameterdirection (name_pk, documentation) VALUES ('in_pim', 'The parameter is an input parameter to the service instance.');_

According to the documentation at https://shapechange.net/transformations/naming-modifier/ it appears that rule-trf-camelcase-to-uppercase is appropriately sensitive to these two class stereotypes, but not rule-trf-add-suffix.  That sensitivity should be added.

**Comment by jechterhoff** [comment]
@pbirkel: How about having a new configuration element, where for a given process rule you define model element selection criteria. The rule would then only be applied to the thus selected model elements. The configuration element would use the same [model element filter functionality as the common transformer for setting tagged values](https://shapechange.net/transformations/common-transformer-functionality/#Model_element_filter_criteria), and [as used by the Descriptor Transformer](https://shapechange.net/transformations/descriptor-transformer/#Model_Element_Selection). 

That configuration pattern could be applied in the future whenever a process (transformation or target) rule can or should be restricted to certain model elements.

For rule-trf-add-suffix, either no `ProcessRuleModelElementSelection` elements are defined in the `advancedProcessConfigurations` element - in which case the current behavior would apply - or the rule would only be applied to the model elements that match one or more of the `ProcessRuleModelElementSelection` elements. Parameter `modelElementNamesToAddSuffixRegex` would then become deprecated. Its presence would be conditional: omit if `ProcessRuleModelElementSelection` elements for the transformation rule are present, require if none are present (current behavior).

This approach would also solve #280 .

**Comment by pbirkel** [comment]
This approach would be a powerful reuse of an existing design pattern, both here and for #280.  The deprecation enabling backwards compatibility is also good.  And the generalized application to all processes would be a nice bit of "future proofing".  I like it :-}.

**Comment by jechterhoff** [comment]
The documentation of the [Naming Modifier transformation](https://shapechange.net/transformations/naming-modifier/) has already been updated with the changes (implemented in the `next` branch).
