### ISSUE TITLE
NamingModifier Transformation: rule-trf-add-suffix and Role Properties

### ISSUE THREAD

**Issue by pbirkel** [ShapeChange/ShapeChange#280]
Ref:  https://shapechange.net/transformations/naming-modifier/#rule-trf-add-suffix 

It seems to me that this rule should only be optionally, if ever, applicable to association roles.  Perhaps it should never be applicable, but my only use-case is the SqlDdl target where in my opinion it shouldn’t be forced to apply.

My justification is based on the following example where I’m using the suffix value="_pim", the modelElementNamesToAddSuffixRegex includes “end” (but not “begin”), and the resulting DDL is:

CREATE TABLE iso19100.timeperiod (
   objid_pk bigserial NOT NULL PRIMARY KEY,
   frame character varying(1024),
   beginposition_fk bigint,
   endposition_fk bigint,
   duration_fk bigint,
   timeinterval_fk bigint,
   begin_timeinstant_fk bigint,
   begin_timepointspecification_fk character varying(254),
   end**_pim**_timeinstant_fk bigint,
   end**_pim**_timepointspecification_fk character varying(254)
);

Regarding the SqlDdl target in no case will the DDL column name resulting from an association role  (_e.g._, “end”) be able to come in conflict with a SQL-based key word except in the case that (1) there is no M:N join table involved, and (2) there is no applied suffix for columns that become keys (1:M association).

Since it seems possible to leave columns without a name-change despite their implementation as a foreign key I can understand why there are circumstances when it might be useful for rule-trf-add-suffix to apply to association roles, but it seems much more likely to me that the derived column/field name will at least contain a foreign-key-suffix of some sort.

In my opinion it would be valuable to enable the flexible application of rule-trf-add-suffix with respect to association roles.

**Comment by pbirkel** [comment]
I agree that the approach proposed for #279 will addressed this issue as well.  I like it :-}.

**Comment by jechterhoff** [comment]
The documentation of the [Naming Modifier transformation](https://shapechange.net/transformations/naming-modifier/) has already been updated with the changes (implemented in the `next` branch).
