### ISSUE TITLE
Tagged Values: Empty vs. Absence

### ISSUE THREAD

**Issue by pbirkel** [ShapeChange/ShapeChange#283]
ShapeChange sometimes treats the presence of an empty TV differently than the absence of that TV. For example TV "base" still triggers behavior if present (perhaps due to an operating MDG implementation of a UML profile in EA) even if empty.  Attempting to permanently delete a TV may fail if the TV was defined by the MDG-based UML profile because  when synchronizing a stereotype in EA, the TV may/will be recreated -- but empty.

SC behavior when checking for TVs should be reviewed and cases identified – and handled appropriately - where an empty value means absence of a value.

**Comment by jechterhoff** [comment]
Good point, thanks for reporting this issue.

**Comment by jechterhoff** [comment]
The code in the `next` branch has been updated.

**Comment by pbirkel** [comment]
Thank you.  Has the online documentation been correspondingly updated to reflect the new/improved/consistent syntactic expectations?  If so, where?

**Comment by jechterhoff** [comment]
Afaics, specific documentation updates were not needed.
