### ISSUE TITLE
Transition to Enterprise Architect (EA) v16

### ISSUE THREAD

**Issue by jechterhoff** [ShapeChange/ShapeChange#295]
We have tested the release candidate of EA v16 in order to determine the compatibility with the current version of ShapeChange, as well as the potentially required changes to ShapeChange.

In order to understand why we opened an issue for this topic, some more background: EA 16 is a 64bit application. Previous versions have been 32bit applications. That in itself is a significant step forward for EA. What is more important is the change in the default EA repository file format. Previously, EAP and EAPX files were used, and that was / is the most prominent use case in combination with ShapeChange. Cloud-based or database EA repositories are a less common use case. With EA v16, the default file format will be SQLite based, having file format extension QEA or QEAX (to my knowledge, the latter is just a designation for cases in which the repository file will be shared across a small team [akin to what was possible with the old file format]). EA v16 no longer appears to directly support modeling in an EAP(X) based repository. Instead, it offers a functionality to transfer such repositories into QEA(X) files (more infos [here](https://sparxsystems.com/enterprise_architect_user_guide/16.0/model_exchange/transfereap.html)).

NOTE: [The EA 16 documentation](https://sparxsystems.com/enterprise_architect_user_guide/16.0/the_model_repository/createamodeloverview.html) states the following: _Note that you cannot create or load a .eap or .eapx file in Enterprise Architect 16.0 64-bit under Wine. Under any other operating system, if the 64-bit access driver is not installed, the system prompts you to convert the file to another format such as .feap._ So far we have not tried installation of a 64-bit access driver. Doing so seems to be a step backwards, when there is clear indication that QEA will become the new standard for file-based EA repositories.

Here is a list of our current findings and test results regarding ShapeChange with EA 16, mostly open tasks:

* We will need to transfer all currently used EAP(X) files to QEA files. That includes (unit) test files (input, reference, etc.) as well as template files.
* We will have to update the ShapeChange configurations - primarily unit tests, but also the one used for testing the ShapeChange installation - to use the new QEA file format in relevant file paths.
* We will have to screen the ShapeChange documentation and source code for occurrences of "eap" (ignoring case), and change to QEA where relevant.
* The utility we have implemented for unit tests that do not create EA repositories, i.e. creating the necessary files for SCXML based execution, appears to still work as expected. We can use it to update the relevant unit test files once the original ShapeChange configurations and eap(x) files of the unit tests have been updated as mentioned before.
* The diff utility for EA repositories needs to be updated (checking for QEA files instead of EAP(x) files). 
* Some parameter names refer to the old file format (i.e., "EAP"). We should probably update these names. We could thereby keep the old names as parameter alias (for some level of backwards compatibility).
* Some parameter default values need to be updated as well, to reflect the file format change.
* We have made some code and unit test modifications to test the execution of ShapeChange with the new QEA file format:
  * In general, the EA Java API (i.e. the EA automation API) seems to still work as expected. So far we only encountered small issues which can be solved (apparently there is a different behavior when writing UML attributes, a model diff - with reference files - showed changes in the values of the length, precision, and scale settings for these attributes).
  * The execution time of unit tests reading UML models from QEA files still is significantly slower than reading from SCXML (compare 418s for QEA based execution of all XSD unit tests vs. 81s for SCXML based execution).

We will need to perform some more tests with the unit tests that write EA repositories (i.e. tests for the UmlModel, ArcGIS Workspace, and SqlDdl targets).

**Comment by jechterhoff** [comment]
It turns out that the 64bit MS Access Database driver actually already is installed on my computer (the ODBC data sources dialog shows it). I therefore tried opening of EAP and EAPX files with EA v16 one more time:

Loading an EAP file failed with following dialog: 
![grafik](https://user-images.githubusercontent.com/4831647/161982461-91696ef4-0d77-4e7e-b753-d1dcc7b6d2d2.png)

Loading an EAPX file actually succeeded.

In any case, QEA appears to be the default with EA v16 (the dialog says as much).

**Comment by jechterhoff** [comment]
Status update:

* It turns out that the transfer of all the EAP(X) files (more than 200, actually) will need to be done manually. In combination with the other tasks described above, that will result in a significant level of effort.
* Right now, there is no urgent need for us to switch to EA 16. Therefore, we will move the upgrade of ShapeChange (to support EA 16) to some point in the future. - When that time has come, we will test if the eaapi.jar, which comes with EA v16, also works with an EA 15 installation. If it does, we can create a new minor release of ShapeChange. If it does not, then we are going to create a minor release that works with EA 15 (containing all the enhancements developed until then), and shortly thereafter a major release that (only) works with EA 16+.

**Comment by heidivanparys** [comment]
I tried to test the automation interface regarding transferring projects, so far with little luck, at least I cannot get it done in a really automated way. See https://sparxsystems.com/forums/smf/index.php/topic,47526.0.html, any input would be welcome.

Note that the release notes for 16.1.1623 state:

> ProjectInterface.ProjectTransfer now accepts .qea and .qeax as Source and Target extensions

So perhaps we are closer to a solution for migrating the test files (provided this transfer can be automated)?

**Comment by jechterhoff** [comment]
@heidivanparys Thanks for following up on this. Let's see what the discussion in the Sparx Systems forum reveals regarding full auotmation with the newest version of EA.

**Comment by jechterhoff** [comment]
Here is an update regarding the test on whether the eaapi.jar, which comes with EA v16, also works with an EA 15 installation. Just tested this with the eaapi.jar from EA v16.1.1624 - 64 bit  (1-Feb-2023), against an installation of EA v15.2.1560  (11-Nov-2021): The ShapeChange unit tests were successfully executed (using the configurations with EA repositories).

**Comment by jechterhoff** [comment]
Support for EA 16.x is available with ShapeChange v3.

**Comment by heidivanparys** [comment]
> Support for EA 16.x is available with ShapeChange v3.

Great news, thanks!
