### ISSUE TITLE
SqlServer explicit comments via sp_addextendedproperty

### ISSUE THREAD

**Issue by jhevenor** [ShapeChange/ShapeChange#306]
I see that there is support for 'comment on X' statements (#83), although I don't believe these are supported by SQL Server.  But, there is support via the `sp_addextendedproperty` function -- see [here](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addextendedproperty-transact-sql).  I'd like to suggest adding this feature. 

The output should be fairly easy to implement with something like this snippet based on `Target/SQL/structure/Comment.java`:

```java
    public String toString() {
    
        StringBuilder sb = new StringBuilder();    
        
        sb.append("EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'");
        sb.append(text.replaceAll("'", "''"));
        sb.append("', @level0type=N'SCHEMA'");
        sb.append(", @level0name=N'dbo'"); // Not sure if there's a variable for schema name
        sb.append(", @level1type=N'TABLE'");
        sb.append(", @level1name=N'");
        sb.append(table);
        sb.append("'");
        if(column != null){
            sb.append(", @level2type=N'COLUMN'");
            sb.append(", @level2name=N'");
            sb.append(column);
            sb.append("'");
        }
        return sb.toString();
    }
```

Functional example: http://tpcg.io/_J84LNE

Sorry for only going halfway, but I'm not familiar enough with the code to know if it needs a SqlServerDdlVisitor, etc.  

Thoughts?     

Thanks for considering.

**Comment by jhevenor** [comment]
@jechterhoff  Thanks for the feedback. 

I agree that the effort might not be worth  the effort at the moment.  I figured it's good to note and throw on the back burner.  If I do code a solution in ShapeChange then I'll be sure to create a pull request.   For now I'll massage in Excel.

**Comment by jechterhoff** [comment]
@jhevenor Ok, sounds good. Then I'll close this issue.
