### ISSUE TITLE
XmlSchema target: Add configuration parameter to control naming of generated Schematron files

### ISSUE THREAD

**Issue by pbirkel** [ShapeChange/ShapeChange#31]
Currently it is the case that ShapeChange names generated Schematron files (for the XSD target) according to the fixed pattern:

schema-full-file-name-with-extension & "_SchematronSchema.xml"

That is:   MySchema.xsd_SchematronSchema.xml

It would be better to drop the ".xsd" from the fixed pattern.

It would be best to provide a parameter to override the fixed pattern with a user-selected name.

**Comment by jechterhoff** [comment]
Supported by parameter [schematronFileNameTemplate](https://shapechange.net/targets/xsd/#schematronFileNameTemplate)
