### ISSUE TITLE
Premature end of file

### ISSUE THREAD

**Issue by jhevenor** [ShapeChange/ShapeChange#313]
I've been running a lot of ShapeChange lately, but today I can't run it at all. I can't recall anything specific that I've changed or updated this week to cause this, but there have been a handful of windows updates, etc. 

I'm working through the [Get Started](https://shapechange.github.io/ShapeChange/2.12.0/get%20started/Get_Started.html) documentation to re-install SC 2.12.  Here is the output I get when running the included test.bat:

```
C:\tools\ShapeChange-2.12.0>java -jar ShapeChange-2.12.0.jar -c https://shapechange.net/resources/test/testXMI.xml
Premature end of file. (line -1, column -1)
ShapeChange has encountered a fatal error and is aborting.
Message:
Error while loading configuration file:
Premature end of file.

C:\tools\ShapeChange-2.12.0>java -jar ShapeChange-2.12.0.jar -c https://shapechange.net/resources/test/testEA.xml
Premature end of file. (line -1, column -1)
ShapeChange has encountered a fatal error and is aborting.
Message:
Error while loading configuration file:
Premature end of file.
PS C:\tools\ShapeChange-2.12.0> java --version
openjdk 17.0.4 2022-07-19
OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8)
OpenJDK Client VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, emulated-client)
PS C:\tools\ShapeChange-2.12.0>
```

I don't know if maybe some the config file references like `https://shapechange.net/resources/test/testEA.xml` are being served differently, or my system has changed.  I'm not quite sure where to even start looking.    Any advice is welcome.

**Comment by cportele** [comment]
@jhevenor - Thanks for reporting. I can confirm that I have the issue, too. I downloaded a fresh copy of the 2.12.0 zip archive and get the same problem (with Java 11), too:

```
% java -jar ShapeChange-2.12.0.jar -Dfile.encoding=UTF-8 -c https://shapechange.net/resources/test/testXMI.xml
Premature end of file. (line -1, column -1)
ShapeChange has encountered a fatal error and is aborting.
Message: 
Error while loading configuration file: 
Premature end of file.

% java -version
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
```

Maybe it has something to do with the access to resources at https://shapechange.net/, but at least some curl requests seemed to look fine. We will have a closer look.

**Comment by jechterhoff** [comment]
The issue was that the ShapeChangeConfiguration.xsd at still used

`<import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>`

instead of

`<import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="w3c/xml.xsd"/>`

That has been fixed now. Could you give it a try, please?

**Comment by jhevenor** [comment]
The test.bat runs again!  Thanks so much.

**Comment by jechterhoff** [comment]
You are welcome. Closing the issue now.
