### ISSUE TITLE
Error writing logs in v2.13

### ISSUE THREAD

**Issue by jhevenor** [ShapeChange/ShapeChange#329]
Just started switching over to use v2.13 and see the following error message:

```
Error: Error while writing XML file. Exception message is: E:\sample\Process1Flattening\Log\SAMPLE.xml (The system cannot find the path specified)
```

My XML input looks something like this:

```xml
<ShapeChangeConfiguration
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns="http://www.interactive-instruments.de/ShapeChange/Configuration/1.1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.interactive-instruments.de/ShapeChange/Configuration/1.1 http://shapechange.net/resources/schema/ShapeChangeConfiguration.xsd">
	<input id="profileABC">
		...
	</input>
	<log>
		<parameter name="reportLevel" value="INFO" />
		<parameter name="logFile" value="E:\sample\Process1Flattening\Log\SAMPLE.xml" />
	</log>
	<transformers>
		...
	</transformers>
	<targets>
         ...
       </targets>
</ShapeChangeConfiguration>
```

The root folder `E:\sample\Process1Flattening\` already existed but all content was removed, and when launching the same process using v2.12 the log file folder just gets created. Two other folders are getting created here, from a FeatureCatalogue target, and an EA.UmlModel target. 

I'm pretty sure if delete the folder all together it will create the log folder, so not a big worry. But figured I should mention it.

**Comment by jechterhoff** [comment]
Thanks for reporting this bug. I can confirm your observation. We changed the way in which XML files (including the one from which the log report is generated) are written in v2.13. Apparently, the code to ensure that the folder structure for such an XML file is created, if it does not yet exist, is insufficient. I'll fix that.

Targets typically have individual checks to ensure that their output folders exist, and create them if that is not the case. However, that is not the case for the log file. So, for the time being, you need to choose the log file path with a folder that either already exists (such as `E:\sample\Process1Flattening\`, in your case), or one that is created by the targets that will be executed.
