### ISSUE TITLE
DiffTarget not mentioned in 2.13.0 release notes

### ISSUE THREAD

**Issue by heidivanparys** [ShapeChange/ShapeChange#330]
I noticed that the functionality described on https://shapechange.github.io/ShapeChange/2.13.0/targets/DiffTarget.html is not mentioned in the [change log](https://github.com/ShapeChange/ShapeChange/blob/master/CHANGELOG.md).

**Comment by jechterhoff** [comment]
You are correct. Apparently, I forgot to create an issue for that enhancement, to ensure that it is noted in the changelog. Therefore, it is good that you created this issue (the changelog for the next version will document it).
