### ISSUE TITLE
ShapeChange-2.9.2

### ISSUE THREAD

**Issue by mirstronout** [ShapeChange/ShapeChange#343]
I am trying to deploy the PODS 7.0.1 model to physical implementation pipeline from PODS dot org.  The distribution comes with a ShapeChange jar with a 2.9.2 label.  Is this a custom version?  Can and should the version be brought to current?

**Comment by jechterhoff** [comment]
Hi @mirstronout. 

We have published version 2.9.1 three years ago, and have not published a 2.9.2 version (maybe your 2.9.2 version was a development snapshot created sometime in between v2.9.1 and v2.10.0). You'd have to ask PODS, if there are any custom extensions in 2.9.2 that are not in the public version of ShapeChange. 

That being said, there have of course been a number of enhancements and bug fixes - see the [changelog](https://github.com/ShapeChange/ShapeChange/blob/master/CHANGELOG.md) for details (enhancements to DDL encoding, new JSON Schema encoding, ldproxy configuration encodings, ...). 

To answer the question whether the version **should** be brought to current, see if you'd like to use any of these enhancements. To determine whether the version **can** be brought to current, you can do a test with the current version, comparing the results with those produced by your version 2.9.2. Clarification whether v2.9.2 contains any PODS-specific extensions would also be relevant.

**Comment by mirstronout** [comment]
Thank you @jechterhoff.

It does look like 2.9.2 is a development snapshot.

I am not sure if the PODS organization knows if they created or have any custom extensions. We will compare the source code to 2.9.1 and 2.10.0 to find out.

The logical PODS model is an EAP file.  My team is using EA v12.1 and the 2.9.2 development snapshot to recreate the documented build, release, and deploy process documented from PODS.  We ran into EA duplicating some names in the XML workspace export process and reverted to EA v12 as a fix.  I believe that particular issue has been resolved but we have not found documentation to confirm.

Your name is in the PODS logical model EAP file, did you help create the original PODS 7 logical model?

My team is working to install the Profile Management Tool, update to ShapeChange v2.13.0 and EA v15, and all of the PODS documentation to reflect more current versions.  Let me know if any of that is advantageous to post or link here.

**Comment by jechterhoff** [comment]
> Your name is in the PODS logical model EAP file, did you help create the original PODS 7 logical model?

Yes, though it was primarily in an advisory role (modeling technique). My focus was more on implementing the ShapeChange workflow and enhancements for PODS.

> My team is working to install the Profile Management Tool, update to ShapeChange v2.13.0 and EA v15, and all of the PODS documentation to reflect more current versions. Let me know if any of that is advantageous to post or link here.

Thanks. A link to the updated documentation, once it is available, would be of interest to the community of ShapeChange users.

**Comment by mirstronout** [comment]
> Yes, though it was primarily in an advisory role (modeling technique). My focus was more on implementing the ShapeChange workflow and enhancements for PODS.

Did you utilize PMT and advise on the ShapeChange workflow for the PODSLite profile?  From my review of the configuration files and ShapeChange documentation, utilizing different ShapeChange profiling tools would serve to simplify and shorten the PODSLite workflow.  I want to make sure I am on the correct path with PODSLite and additional profile work to extend PODS 7.0.1.

**Comment by jechterhoff** [comment]
Yes, I did advise on defining the ShapeChange workflow, and helped with the configuration options; also implemented a couple of extensions to ShapeChange.

At the time (2016), the model itself contained the profile definitions. The PMT (which was developed later on) can help simplify the task of defining a profile (for further details, see the documentation: [Profiling](https://shapechange.github.io/ShapeChange/2.13.0/transformations/profiling/Profiling.html) and [Profile Transfer to EA Repository](https://shapechange.github.io/ShapeChange/2.13.0/targets/Profile_Transfer_to_EA_Repository.html)). Migrating profile definitions between different versions of a model can, however, be a complex task.

**Comment by mirstronout** [comment]
@jechterhoff your responses make me feel better about the time I spent tracing the profiles in the model and confirm my thoughts on direction of updates.
