### ISSUE TITLE
Test resources on shapechange.net not yet updated

### ISSUE THREAD

**Issue by heidivanparys** [ShapeChange/ShapeChange#354]
The test resources on https://shapechange.net/resources/test/ are not yet updated after the release of v3.0.0, which includes #295. So when following the instructions on https://shapechange.github.io/ShapeChange/3.0.0/get%20started/Get_Started.html, file test/test.eap is not found and ShapeChange fails with the following:

```
F Enterprise Architect repository file named 'test/test.eap.qea' not found
ShapeChange has encountered a fatal error and is aborting.
```

**Comment by jechterhoff** [comment]
Thank you for reporting this. The online resources (tests and examples) have been fixed (adding the .qea files, and switching the file extension in the ShapeChange configurations from .eap to .qea).
