### ISSUE TITLE
JsonSchemaTarget generates invalid schema if enum has single entry

### ISSUE THREAD

**Issue by JDziurlaj** [ShapeChange/ShapeChange#360]
With a SCXML class entry like 

```xml
<sc:Class>
	<sc:name>CastVoteRecordVersion</sc:name>
	<sc:id>_18_0_2_6340208_1488984734564_983877_4662</sc:id>
	<sc:stereotypes>
		<sc:Stereotype>enumeration</sc:Stereotype>
	</sc:stereotypes>
	<sc:properties>
		<sc:Property>
			<sc:name>1.0.0</sc:name>
			<sc:id>_18_0_2_6340208_1488984746812_574391_4681</sc:id>
			<sc:sequenceNumber>1</sc:sequenceNumber>
		</sc:Property>
	</sc:properties>
</sc:Class>
```
generates a JSON Schema with a corresponding definition

```json
"CastVoteRecordVersion": {
			"$anchor": "CastVoteRecordVersion",
			"type": "string",
			"enum": "1.0.0"
		},
```

which is invalid. The value of the key `enum` should be an array, i.e. `["1.0.0"]`, even if there is only a single value in the enumeration.

**Comment by jechterhoff** [comment]
@JDziurlaj Thank you for reporting this bug. I've just pushed a fix. A new Shapechange snapshot is available [here](http://shapechange.net/resources/dist/ShapeChange-3.0.1-SNAPSHOT.zip).
