### ISSUE TITLE
Old version of Saxon

### ISSUE THREAD

**Issue by heidivanparys** [ShapeChange/ShapeChange#361]
The version of Saxon that is referred is a couple of years old. Can it be updated to 12.4, or is this a particular reason for the older version?

https://github.com/ShapeChange/ShapeChange/blob/c9b38dc9f89cdd88df8e7cad4c9dba81ecc6c705/pom.xml#L158-L161.

**Comment by jechterhoff** [comment]
There is no particular reason for Saxon-HE version 10.2. That version has just "fit the purpose" thus far. An upgrade should be possible. Do you need v12.4 for a particular reason?

**Comment by heidivanparys** [comment]
No, not a particular reason, just a general increased focus on keeping software and their dependencies up-to-date.

**Comment by jechterhoff** [comment]
I'll see what I can do regarding the dependency update.

**Comment by jechterhoff** [comment]
The dependencies have been updated (branch 'next'). 

Dependabot is configured so that we can more easily keep the dependencies up-to-date from now on.

**Comment by heidivanparys** [comment]
Great, thanks!
