### ISSUE TITLE
SQL DDL target - names of check constraints can collide in Oracle

### ISSUE THREAD

**Issue by heidivanparys** [ShapeChange/ShapeChange#44]
Oracle constraints in an Oracle schema have their own namespace and have a maximum length of 30.

Currently, the names of check constraints are generated by concatenating a truncated version of the table name with a truncated version of the feature type. This may result in name collisions when using similar table names ( e.g. tablesuffix1, tablesuffix2, ...) and long column names where the first part is the same (businessevent, businessprocess, ...).

I see two requirements:
* Making sure sure that constraints names are unique and have a maximum length of 30.
* Make the generation of constraints names as independent as possible from any changes in the model that are unrelated to these constraints.

A clarification of the second requirement:
* It is ok that the name of the constraint changes when the related table or the related column changes name (because of a name change in the UML model e.g.).
* Preferably, the name of the constraint does not change when e.g. the order of attributes in the UML changed, or when the UML model was reloaded in Enterprise Architect and the internal IDs were changed there, resulting in a different order of processing of UML entities in ShapeChange.

The main advantage of this is that a pure textual diff of a DDL file with a DDL file generated earlier is made easier. This way, people who generate DDL files but do not have the tools, time nor responsibility to actually implement the DDL and compare it with an earlier implemented version, can do a quick visual check by doing a textual diff, to see that the changes made in the model are reflected and no unintended changes sneaked in.

This issue is related to #39 .

**Comment by jechterhoff** [comment]
In the commit to #39 we introduced a new conversion rule for naming of foreign key constraints. If that rule is insufficient for the conversion of a given application schema we can add another rule (suggestions welcome).

**Comment by heidivanparys** [comment]
Issue #39 is about foreign key constraints, the same applies to check constraints (the ones added by ShapeChange are derived from the enumerations in the model).

I am aware of the changes done in the commit to #39 , and have the following remarks to that:
- all constraints of a schema share one namespace, that is, the name of a check constraints can possibily collide with the name of a foreign key constraint
- that commit doesn't take into account the second requirement explained in this issue description
- is there is a specific reason why the generation of foreign key constraints is done in SqlDdl, and not in the DatabaseStrategy classes, when applying the oracle naming style?

The solutions try to solve (part of) similar problems, so I hope we can find a way to fulfill the requirements of your project and our requirements. #47 is just a proposal, I created a pull request to invite to a discussion (which of course also can be take place on this issue).

**Comment by jechterhoff** [comment]
This is solved by the introduction of several naming strategies. For further details, see http://shapechange.net/targets/sql-ddl/#Naming.
