### ISSUE TITLE
Slash vs hash in UML-to-OWL conversion

### ISSUE THREAD

**Issue by nataschake** [ShapeChange/ShapeChange#467]
Hi!
I convert UML file into OWL, and in the config define explicitly target namespaces ended with slash, e.g. 
```
<targets>
<TargetOwl...>
<Namespace nsabr="app" ns="https://www.opengis.net/ont/citygml/appearance/"/>
...
```
in the resulting ttl files I find that namespace ended with hash:

`@prefix app: <https://www.opengis.net/ont/citygml/appearance#> .`

Is it a fixed behavior and I should apply postprocessing step to replace those hashes with (expected) slashes?
Or is there a parameter to turn on to get the desired results automatically?

**Comment by jechterhoff** [comment]
It works for me for cases where the `<Namespace>` element is defined for RDF map entries.

If the namespace you declared is for an application schema that is actually encoded to an ontology by ShapeChange, then you can try setting target parameter `rdfNamespaceSeparator` to `/` (default value is `#`).

**Comment by nataschake** [comment]
Thanks, I confirm working solution with 
`      <targetParameter name="rdfNamespaceSeparator" value="/"/>`
