### ISSUE TITLE
Question UML profile test models

### ISSUE THREAD

**Issue by heidivanparys** [ShapeChange/ShapeChange#50]
Is it possible that a UML profile with name ShapeChange is used in all the test modes? When querying some of the models in src/test/resources, the following came up:

![image](https://cloud.githubusercontent.com/assets/11427611/21717599/4d750eba-d412-11e6-9ce2-5780fee74e6f.png)

If yes, would it possible to provide it via GitHub (on the wiki?)? It would be useful when adding more tests and creating test models for them.

**Comment by jechterhoff** [comment]
Yes, we do have an MDG called ShapeChange. It's not used in all test models, but I tend to use it for new models. I'll add the MDG files to the repository. The MDG covers the basics - suggestions for improvements in future versions are welcome.

**Comment by jechterhoff** [comment]
The MDG can be found in https://github.com/ShapeChange/ShapeChange/tree/master/src/main/resources/MDG
