### ISSUE TITLE
Namespace for ISO 19150-2

### ISSUE THREAD

**Issue by cportele** [ShapeChange/ShapeChange#92]
See https://github.com/ISO-TC211/GOM/issues/2

All occurances of http://def.isotc211.org/iso19150-2/2012/base# need to be replaced by http://def.isotc211.org/iso19150/-2/2012/base# (extra "/" before the "-2").

**Comment by jechterhoff** [comment]
Is that namespace change going to be added as a fix to the official standard? Afaics the standard uses http://def.isotc211.org/iso19150-2/2012/base#

**Comment by cportele** [comment]
> Is that namespace change going to be added as a fix to the official standard? Afaics the standard uses http://def.isotc211.org/iso19150-2/2012/base#

Maybe, I only have drafts, not the final standard. However, what is used in practice is the ontology that is available online, so de-facto this specifies the namespace, etc. Which is why OGC has the policy that the online schema/ontology/etc. takes precedence over the standards document. (I doubt that ISO has a similar policy, but the reality is still that this is the case.)

> ... in any case, I guess it's better to make all namespaces configurable, including the ones defined by standards which are currently hard-coded.

Yes, it should not have been necessary, but this shows that it probably is better to make them all configurable.

**Comment by jechterhoff** [comment]
The document is inconsistent regarding the namespace for the ISO 19150-2 ontology:

* In section 4.3 "Namespaces" iso19150-2 is used (in the draft, and apparently also in the published version, at least [the online browsing platform](https://www.iso.org/obp/ui/#iso:std:iso:19150:-2:ed-1:v1:en) indicates this). Same in Annex E (informative example).
* In Table 9 import of the ontology denoted http://def.isotc211.org/iso19150/-2/2012/base is required. The ontology with that name - and the namespace http://def.isotc211.org/iso19150/-2/2012/base# - is also given in Annex D (normative).

We'll use the iso19150/-2 namespace as default.
